### PR TITLE
Fix Graphics for Warehousing

### PR DESCRIPTION
**Pull request by hgschmie**
Factorio 2.0 no longer uses the "hr" variant but uses high resolution
graphics everywhere and scales them down accordingly. Change all the
base images to the HR versions and update the prototypes.

### CODE REVIEW

**Comment by dgw** [comment]
Is there a reason not to delete references to "hrimg" etc. instead of the "img" versions, and reorganize the image files (rename `hr-X` to just `X` and delete the old, smaller sprites)?

Please be consistent with your whitespace; some changes add spaces instead of tabs.

**Comment by dgw** [comment]
And to clarify, the main issue with the current release is that _lower-resolution_ (non-`hr`) sprites simply aren't used, right? I am OK with a bit of extra .zip bloat in the 1.0.1 release planned for this weekend, and do not plan to rush this through unless something is truly "broken" in-game (which I haven't noticed in testing).

**Comment by hgschmie** [comment]
hey, thanks for the quick response.

I tried to do the minimal invasive patch. Yes, renaming the images, dropping the low res images etc. is all fine; I just did not want to do that for the PR. If you rename the images, the various parameters from the hr images (width, height) need to be moved over. 

I used "format region" in VSCode, guess it did not pick up the indent style for the project. Sorry 'bout that.

**Comment by dgw** [comment]
Interesting, VSC has been good about indentation for me. Still doesn't keep me from just running `luafmt` if I'm feeling extra sassy :smile_cat:

I think it's worth taking the time to do it "right", and only do it once. If you're willing to do the rest of the cleanup, great! Or I'll take a look after we get 1.0.1 out.

**Comment by hgschmie** [comment]
I fixed the indentation (M-x tabify is your friend). 

I can also do the renames / drop the low res versions.

**Comment by dgw** [comment]
Let's do that, move the `hr-` sprites over their smaller counterparts and remove the `hr` prefix from `chestAnim` parameters.

I'll be back for a :mag_right: look after 1.0.1's out, because that loading error in game version 2.0.16 can't wait for anything else to be ready.

**Comment by hgschmie** [comment]
I updated the graphics.

**Comment by hgschmie** [comment]
Any updates on this?

**Comment by Anoyomouse** [comment]
Sorry, haven't gotten to review this yet, it's been a bit of a hectic time, I'll review it soon :)

**Review by dgw — APPROVED** [review]
So I took care of the visual comparison part of this:

| Before | After |
|--------|-------|
| image      | image     |

(And this time I actually got a screenshot tool with a "repeat last capture" function.)

Cloud shadows aside, I think it's clear that this PR (on the right) is an improvement.

Nothing jumps out at me in the code changes, but I'd still prefer to get a second opinion from @Anoyomouse before merging. Hopefully soon, so we can move on to fixing #120.

**Comment by dgw** [comment]
OK, let's do it.

**Pull request merged**
