### PR TITLE
Description manipulation

### PR DESCRIPTION
**Pull request by JDOGG88**
Just the initial PR with the basic concatenation code.

### CODE REVIEW

**Comment by JDOGG88** [comment]
I know you'd like a variable/placeholder within the string which makes sense for how other languages might be read.  I'm just not sure how to go about that to where it would "move" the variable based on locale or if I'm misunderstanding what your getting at.  Could you maybe give me an example to idea to give me a place to start like you did with fixing the createLogisticContainer function?

**Comment by dgw** [comment]
First of all, this PR appears to include all of #68. The point of making a separate PR was to separate the description changes, wasn't it?

Translations with placeholders are one of those things that I looked into, but couldn't figure out, so I'm afraid I have no starting point to give you just yet. :frowning_face:

I _know_ the base game uses placeholders in some of its localizations, but those might only work in places where the text is "printed" or something (like the chat console, or in a GUI element). If you can track down how it works for `filled-barrel` (the only `item-description` I could find in the base locale files that uses `__1__`), that might help. I ran out of time looking for it just now, and it might be handled in C++ code that we don't have access to instead of in a Lua file.

**Comment by JDOGG88** [comment]
I need to stop trying to work on it when I'm tired lol. I was like oh this totally make sense to have all the changes in one thing haha sorry.  This push should have it with only the changes to the base master and I tweaked my original idea slightly to add the "local localeDescription = {"item-description.warehousing-description"}" line in the hopes that it will be easier to use placeholders with it.  Not sure if it's a good idea or not but hopefully it will make it easier.

**Comment by JDOGG88** [comment]
I got it to work and tested it in game so the only thing that would need to be worked out would be manipulating where the place holder would be used in the different locale.cfg files. ^_^

**Comment by Anoyomouse** [comment]
Hey, I like the fact you figured out how to do substitution, however i don't believe adding the slot count to the descriptions add any value to the mod. The tool tip already contains a capacity, and i think this really defeats the point of having the whole localization thing, as well as, in Chinese and Asian languages, it'll put a roman numeral (i'm guessing), which will just look out of place.

I know you've spend a whole bunch of time on this, but yeah, dunno if it adds value, and if it's worthwhile adding .. just my 2c

**Comment by JDOGG88** [comment]
I totally get where you're coming from, it was more my OCD wanting to figure it out more than anything else.  I wouldn't see why it would show a Roman numeral for other languages though as it references the variable of what slots the container has.  Unless their languages won't show numbers in the same way as English and have totally different characters all together.  Even then though it would show the same numerical value as it does in the tooltip.  The tooltip isn't displayed when you mouse over an entity that has already been created which is the main reason i wanted to do it so you can see it without having to go and check the character screen. I'm cool with whatever you guys decide to do, just giving my reasoning behind what I was trying to accomplish.  Definitely appreciate any input though ^_^

**Comment by dgw** [comment]
Almost two years later and I'm still not entirely sure what this would accomplish. Slot count is visible when the cursor hovers over a placed entity, and in the crafting menu, and in the inventory:

image image image

Even if it was hard to find the storage size of a placed warehouse before, in Factorio 1.1 it's quite obvious.

**Pull request closed without merging**
