### PR TITLE
Cosmetic Changes

### PR DESCRIPTION
**Pull request by JDOGG88**

### CODE REVIEW

**Comment by dgw** [comment]
Force-pushed to remove the ten irrelevant commits. I will test these in-game probably tomorrow; it's supposed to snow a lot, so I'm sure there will be plenty of free time to be had. :grin:

Your `master` branch should never _merge_ changes from upstream, or it will gain irrelevant commits that clutter pull request branches. A fork's default branch (usually `master`) should ideally only ever be _behind_ its upstream. This shouldn't happen: "This branch is 10 commits ahead of Warehousing:master." But that's what your `master` branch says right now.

I know it isn't really your fault—you're using a GUI tool, and that tool probably did this when you asked it to synchronize your branch—but you really should fix that `master` branch so future PRs don't have this problem. It's relatively easy to do via Git commands, but I couldn't easily find a way to do it in IntelliJ.

```bash
cd /path/to/warehousing/fork
git checkout master
git fetch upstream
git reset --hard upstream/master
git push -f origin master:master
```

Replace `main-repo-remote` with the name of this repo. If you don't know it, `git remote` will show you the remotes you have (probably `origin` for your fork, which is the default name; and one for this repo).

None of those commands can change this branch. Specifying `master:master` in the push command ensures that it will only push _from_ local `master` _to_ remote `master`, and nothing else.

**Comment by dgw** [comment]
OK, while I was fixing #68 so it could be reopened, I also fixed your `master` branch. :smile_cat:

Use `git checkout master && git fetch origin && git reset --hard origin/master` to point your local `master` so it matches upstream.

**Comment by dgw** [comment]
This is a pretty subtle change, now that I had a chance to test it out.

I guess the goal was to match which side of the pole wires go on when stringing them along power lines? It works in most cases, though there are some rotations of the power poles that swap the colors.

Should probably do something about the "floating" wires when connected to basic storehouse/warehouse buildings, since their sprites don't have the connection points, but not necessarily in this PR.

**Comment by JDOGG88** [comment]
Yeah that was the goal and the wires were offset from the antennas ever so slightly and I tried to make the shadow's a bit more accurate as well.  

As far as the floating wires go I don't think it would be too difficult to add just the antenna to the basic buildings if new models aren't planned to be made.  I know you had assigned updating them to whoever had the original models and it would be super easy to do that while updating those.  If the models are going to change at all it might be better to wait until those changes have been completed.

**Comment by dgw** [comment]
I'm told Nova Kast is "excited" about making overhauled models, and we might even get an animation for when robots stop at a building. Factorio recently added a way to specify where robots should stop relative to a logistic container (the `LogisticContainerPrototype::landing_location_offset` added [in 0.17.5](https://forums.factorio.com/66705)), so we should be able to make some fancy stuff eventually.

Rather than adding the antenna, I was thinking of having the basic buildings use a circuit connector box, like regular chests do. Ran out of time when I started tracing through the base entities to see how they invoke one, but it should be possible. Would probably look better than adding the antennas, too.

**Comment by JDOGG88** [comment]
It would be sweet if we could give them the same or similar animation as the vanilla chests where the portal opens and closes when the robots interact with them.

If he does that or manipulates the models and if you do plan to add in the small/tiny versions it would be awesome if he could generate the sprites in the different sizes needed.

I also totally agree it would look better to have them use the default circuit connector box.  It would just be a matter of manipulating where the box itself was generated on the sprite.  I've never messed with that so I have no idea how to do that but I'd be willing to try and figure it out.  Would you happen to know off the top of your head what it's called or if it's even possible to manipulate?

**Comment by JDOGG88** [comment]
I figured it out, once I tweak it and get it to look right I'll open a new PR with my cosmetic-changes branch.  I know the models may change but doing it will at least give us a base to work from when the models do change.

Also you may even want to pull the changes in before the new version is released with the new models.

**Comment by JDOGG88** [comment]
image

Got it to look pretty decent, still some work to do and it add's a lot of lines of code so I'm going to try to reduce that with a function if I can.

**Pull request merged**
