### PR TITLE
add startup setting, scale inventory icons

### PR DESCRIPTION
**Pull request by Yousei9**
- added startup setting scale inventory icons
- added English locale for setting 
- added German locale for setting

### CODE REVIEW

**Comment by Yousei9** [comment]
Funny, you want to keep tailing , at tables for further expansions, but remove order strings making expanding awkward.

**Comment by Yousei9** [comment]
I had added german translation

**Comment by dgw** [comment]
If the mod ever adds more settings and the order actually becomes important, it can always be added again. Leaving out `order` now isn't _that_ big a deal.

> I had added german translation

Not for the setting description, which didn't exist until a moment ago.

**Comment by Yousei9** [comment]
I see. 
Descriptions are where I struggle most. I hope this one is understandable to anyone who isn't me.

**Comment by dgw** [comment]
Let's do it. I want to see if Crowdin explodes…

**Pull request merged**
